services:
  backend:
    name: Backend API
    description: Node.js Express API server
    triggeredBy:
      - postDevcontainerStart
    commands:
      start: |
        cd /workspaces/workshop/backend
        
        echo "Installing backend dependencies..."
        npm install
        
        # Initialize SQLite database
        echo "Initializing SQLite database..."
        node init-db.js
        
        echo "Starting backend API..."
        npm start
      
      ready: |
        # Check if backend API is responding
        curl -f -s http://localhost:3001/api/health > /dev/null
      
  # frontend:
  #   name: Frontend Dev Server
  #   description: React + Vite development server
  #   triggeredBy:
  #     - postDevcontainerStart
  #   commands:
  #     start: |
  #       cd /workspaces/workshop/frontend
        
  #       echo "Installing frontend dependencies..."
  #       npm install
        
  #       # Expose port 3000 publicly
  #       echo "Exposing port 3000..."
  #       gitpod environment port open 3000 --name "Frontend" --protocol http --dont-wait
        
  #       echo "Starting frontend dev server..."
  #       npm run dev
      
  #     ready: |
  #       # Check if frontend dev server is responding
  #       curl -f -s http://localhost:3000 > /dev/null
      
  #     stop: |
  #       # Close the exposed port
  #       gitpod environment port close 3000 || true
  #       # Stop frontend dev server (npm run dev runs in foreground, will be killed by automation)
  #       echo "Frontend dev server stopped"